#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server

if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
  exit 1
fi

if [ $# -eq 4 ]; then
  ssh_options="-i $4"
else
  ssh_options=""
fi

scp -o StrictHostKeyChecking=no $ssh_options $1 $3@$2:~
