#!/usr/bin/env bash
#script that configures a new Ubuntu machine to listen on port 80
#it must return a page that contains the string Hello World!

sudo apt-get update
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
sudo service nginx restart
