#!/usr/bin/env bash
# Script that configures Nginx server to redirect to another page

string_for_replacement="server_name _;\n\nlocation\/redirect_me
                        {\n\treturn 301 https:\/\//www.youtube.com;\n}"
sudo sed -i "s/server_name _;/$string_for_replacement/"
/etc/nginx/sites-available/default

service nginx restart
