#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page with message.

#Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

#Create sample page and add defalt server blocks
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html

#add default server block
string_for_replacement="server_name_;\n\trewrite '\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name_i/$string_for_replacement/" "etc/nginx/sites-available/default"

#Redirect error
echo "Ceci n'est pas une page" > /var/www/html/404.html
string_for_replacement="listen 80 deafult_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" "/etc/nginx/sites-available/default"

#Restart Nginx
service nginx restart
