#!/usr/bin/env bash
#configure web-02 to be identical to web-01,add custom Nginx response header

#Install Nginx
sudo apt-get -y update
sudo apt-get install -y nginx

#HTTP header config
sudo sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

#Configure the Nginx and Create sample page
ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.html

#error page and redirect error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#Restart Nginx
nginx -s reload
