#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

#Install HAproxy
sudo apt-get update -y
sudo apt-get -y install haproxy

#Configure HAproxy
echo "
frontend kay-front
	bind *:80
	default_backend kay-back
	
backend kay-back
	balance roundrobin
	server 180378-web-01 54.236.12.12:80 check
	server 180378-web-02 54.82.134.241:80 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

#Restart HAproxy
sudo service haproxy restart
